CREATE TABLE Zanrid (
ID INT PRIMARY KEY IDENTITY,
Nimetus NVARCHAR(25) NOT NULL
);

CREATE TABLE Vanusepiirangud (
ID INT PRIMARY KEY IDENTITY,
Nimetus NVARCHAR(25) NOT NULL
);

CREATE TABLE Rezissoorid (
ID INT PRIMARY KEY IDENTITY,
Taisnimi NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Filmid (
ID INT PRIMARY KEY IDENTITY,
Nimetus NVARCHAR(50) NOT NULL,
Kirjeldus TEXT NOT NULL,
Kestus INT NOT NULL,
Väljalaskeaeg DATE NOT NULL,
Poster VARBINARY(MAX) NOT NULL,
RezissoorID INT NOT NULL,
ZanrID INT NOT NULL,
VanusepiirangID INT NOT NULL,
FOREIGN KEY (RezissoorID) REFERENCES Rezissoorid(ID),
FOREIGN KEY (ZanrID) REFERENCES Zanrid(ID),
FOREIGN KEY (VanusepiirangID) REFERENCES Vanusepiirangud(ID)
);

CREATE TABLE Kinod (
ID INT PRIMARY KEY IDENTITY,
Nimetus NVARCHAR(50) NOT NULL,
Aadress NVARCHAR(100) NOT NULL
);

CREATE TABLE Saalid (
ID INT PRIMARY KEY IDENTITY,
Nimetus NVARCHAR(25) NOT NULL,
Tuup NVARCHAR(25) NOT NULL,
KinoID INT NOT NULL,
VeerudArv INT NOT NULL,
ReadArv INT NOT NULL,
FOREIGN KEY (KinoID) REFERENCES Kinod(ID)
);

CREATE TABLE Keeled (
ID INT PRIMARY KEY IDENTITY,
Nimetus NVARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE Seanssid (
ID INT PRIMARY KEY IDENTITY,
Aeg DATETIME NOT NULL,
FilmID INT NOT NULL,
KeelID INT NOT NULL,
SaalID INT NOT NULL,
FOREIGN KEY (FilmID) REFERENCES Filmid(ID),
FOREIGN KEY (KeelID) REFERENCES Keeled(ID),
FOREIGN KEY (SaalID) REFERENCES Saalid(ID)
);

CREATE TABLE Istmed (
ID INT PRIMARY KEY IDENTITY,
Rida INT NOT NULL,
Veerg INT NOT NULL,
SaalID INT NOT NULL,
FOREIGN KEY (SaalID) REFERENCES Saalid(ID),
UNIQUE (SaalID, Rida, Veerg)
);

CREATE TABLE SeanssiIstmed (
ID INT PRIMARY KEY IDENTITY,
KasOnHõivatud BIT NOT NULL DEFAULT 0,
SeanssID INT NOT NULL,
IstmedID INT NOT NULL,
FOREIGN KEY (SeanssID) REFERENCES Seanssid(ID),
FOREIGN KEY (IstmedID) REFERENCES Istmed(ID),
UNIQUE (SeanssID, IstmedID)
);

CREATE TABLE Kontod (
ID INT PRIMARY KEY IDENTITY,
Huudnimi NVARCHAR(50) NOT NULL,
Email NVARCHAR(100) NOT NULL UNIQUE,
Parool NVARCHAR(25) NOT NULL,
Tuup NVARCHAR(25) NOT NULL,
);

CREATE TABLE Piletid (
ID INT PRIMARY KEY IDENTITY,
Hind DECIMAL(5, 2) NOT NULL,
SeanssiIstmedID INT NOT NULL,
KontoID INT NOT NULL,
FOREIGN KEY (SeanssiIstmedID) REFERENCES SeanssiIstmed(ID),
FOREIGN KEY (KontoID) REFERENCES Kontod(ID)
);

INSERT INTO Kontod (Huudnimi, Email, Parool, Tuup) 
VALUES ('Kasutaja', 'Kasutaja', '1234', 'Kasutaja');

INSERT INTO Kontod (Huudnimi, Email, Parool, Tuup) 
VALUES ('Admin', 'Admin', '1234', 'Admin');